services:
  db:
    build: ./db
    image: ttappostgres
    container_name: tta_db
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasktablemtab
    ports:
      - "5433:5432"
