spring:
  profiles.active: dev
  application.name: TaskTableApp
  datasource:
    #url: jdbc:postgresql://db:5432/tasktablemtab <- taki adres żeby działał w kontenerze
    url: jdbc:postgresql://localhost:5433/tasktablemtab
    username: user
    password: password
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  #Baza nie jest modyfikowana i przystosowywana do kodu
    hibernate.ddl-auto: none

logging.level:
  root: INFO